language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
env:
  - PACKAGE=web-api
  - PACKAGE=rtm-api
  - PACKAGE=webhook
  - PACKAGE=types
  - PACKAGE=logger
  - PACKAGE=client
  - PACKAGE=integration-tests
install:
  - npm install
  - lerna bootstrap --no-ci
script:
  - lerna run test --scope $PACKAGE
  - lerna run lint --scope $PACKAGE
after_success:
  - lerna run coverage --scope $PACKAGE
