# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
product_name: &product_name Slack Developer Kit for Node.js
title: *product_name
email: opensource@slack.com
baseurl: /node-slack-sdk
url: https://slack.dev
repo_name: node-slack-sdk
github_username: SlackAPI

code_of_conduct_url: https://slackhq.github.io/code-of-conduct
cla_url: https://cla-assistant.io/slackapi/node-slack-sdk

google_analytics: UA-56978219-13
google_tag_manager: GTM-KFZ5MK7

include:
  - _general
  - _packages
  - _tutorials

# Placing reference pages in a collection allows them to be enumerated for the sidebar
collections:
  reference:
    output: true # collection pages aren't turned into files for the static build unless this is set

# Build settings
markdown: kramdown
plugins:
  - jemoji
  - jekyll-redirect-from

# Obtain github metadata when building locally
repository: slackapi/node-slack-sdk
