# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
product_name: &product_name Slack Developer Kit for Node.js
title: *product_name
email: opensource@slack.com
baseurl: /node-slack-sdk
url: https://slack.dev
repo_name: node-slack-sdk
dev4slack_channel: sdk-node-slack-sdk
twitter_username: SlackAPI
github_username:  SlackAPI

google_analytics: UA-56978219-13
google_tag_manager: GTM-KFZ5MK7

include: ['_pages']

collections:
  reference:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jemoji
  - jekyll-redirect-from

# Obtain github metadata when building locally
repository: slackapi/node-slack-sdk
